import Head from "next/head";
import Image from "next/image";
import Chat from "../components/Chat";
import Sidechat from "../components/Sidechat";
import Sideicon from "../components/Sideicon";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Chat UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Sideicon />
        <Sidechat />
        <Chat />
      </main>
    </div>
  );
}
